WINTER ARC JOURNEY STARTS HERE !❄️

Learning Resource : [Data Analysis with Python by freecodecamp](https://www.freecodecamp.org/learn/data-analysis-with-python/)

BASICS OF NUMPY

In [1]:
import numpy as np

In [3]:
a=np.array([1,2,3])

In [5]:
print(a[0])

1


In [7]:
a[1:2]

array([2])

In [13]:
a[[0,2]]

array([1, 3])

array types

In [15]:
a.dtype

dtype('int64')

SHAPE

In [17]:
matrix=np.array([[1,2,3,4],
                  [4,1,2,3],
                  [5,6,1,3]])
matrix

array([[1, 2, 3, 4],
       [4, 1, 2, 3],
       [5, 6, 1, 3]])

In [18]:
matrix.shape

(3, 4)

In [19]:
matrix.size

12

SLICING MATRICES

To get the first elemnet of second row

In [20]:
matrix[1][0]

np.int64(4)

In [21]:
matrix[:,:2]

array([[1, 2],
       [4, 1],
       [5, 6]])

In [22]:
matrix[:2,:2]

array([[1, 2],
       [4, 1]])

In [23]:
matrix[:2,2:]

array([[3, 4],
       [2, 3]])

Arithmetic

In [24]:
a=np.array([1,2,3])

In [25]:
a.sum()

np.int64(6)

In [26]:
a.mean()

np.float64(2.0)

In [27]:
a.std()

np.float64(0.816496580927726)

In [28]:
a=np.array([[1,2,3],
           [3,4,5]])

In [30]:
print(a.sum(axis=1))
print(a.mean(axis=1))
print(a.std(axis=1))

[ 6 12]
[2. 4.]
[0.81649658 0.81649658]


In [31]:
print(a.sum(axis=0))
print(a.mean(axis=0))
print(a.std(axis=0))

[4 6 8]
[2. 3. 4.]
[1. 1. 1.]


Arange()

In [33]:
a=np.arange(5)
a

array([0, 1, 2, 3, 4])

vector operations

In [34]:
a + 10

array([10, 11, 12, 13, 14])

In [35]:
a*2

array([0, 2, 4, 6, 8])

MODIFICATION

In [36]:
a

array([0, 1, 2, 3, 4])

In [37]:
a+=2

In [38]:
a

array([2, 3, 4, 5, 6])

Boolean Arrays

In [40]:
a=np.arange(4)

In [41]:
a

array([0, 1, 2, 3])

In [42]:
a>=1

array([False,  True,  True,  True])

In [43]:
a[a>=1]

array([1, 2, 3])